### ISSUE TITLE
Key error on line 29 with detecting winner

### ISSUE THREAD

**Issue by MagTheDev** [Magiccop990/School#1]
Traceback (most recent call last):
  File "d:/Python/Test/T/Main/RNG.py", line 31, in <module>
    GetNameOfNum(wwchd)
  File "d:/Python/Test/T/Main/RNG.py", line 29, in GetNameOfNum
    winner = dct_index[wwchd]
KeyError: 3063

**Comment by Streamer272** [comment]
Skus to do toho wwchd zapisivat ako int a potom ked to printujes daj print(str(wwchd))

**Comment by ivanhrabcak** [comment]
Chyba je v pouzivani mapy (dictionary). Ak získavaš value priamo - `dictionary["key"]` a "key" v sa v slovníku nenachádza, python vyhodí `KeyError`. Toto sa dá predísť ak použiješ get() - `dictionary.get("key")`, ak sa "key" v slovníku nenachádza, vráti sa ti None.

**Comment by MagTheDev** [comment]
Resoved
