### ISSUE TITLE
No File Found error @ l39

### ISSUE THREAD

**Issue by MagTheDev** [Magiccop990/School#6]
No file found error occurring on line 39.
Possible solutions: open("whole path to file", "r")

**Comment by ivanhrabcak** [comment]
https://github.com/Magiccop990/School/blob/6d918701910b8536cdf00542798024a02ad30779/RNG#L36
V pythone znamena `\` escape, nie je to opacne lomitko. Pouziva sa na speciane charactery, (`\n`, `\r.`...)
Cestu suboru v tomto riadku python nevie precitat, nevidi opacne lomitka ale `\P` `\T` `\T` `\M` a `\R`.
Na to, aby python precital cesty s opacnymi lomitkami ju mozes napisat takto:
`"D:\\Python\\Test\\T\\Main\\RNG"` alebo vymenit opacne lomitka za normalne.

**Comment by MagTheDev** [comment]
Resolved
