### ISSUE TITLE
Permission Error @ l37

### ISSUE THREAD

**Issue by MagTheDev** [Magiccop990/School#9]
Traceback (most recent call last):
  File "d:/Python/Test/T/Main/RNG/RNG.py", line 37, in <module>
    sfile = open("D:\Python\Test\T\Main\RNG", "r")
PermissionError: [Errno 13] Permission denied: 'D:\\Python\\Test\\T\\Main\\RNG'
Possible solutions: Dont have any clue

**Comment by ivanhrabcak** [comment]
Kedze python hlada cesty v priecinku v ktorom sa prave nachadzas, nemusis vsade davat cele cesty, ak nemas istotu mozes uistit cez `os.getcwd()` co ti vrati celu cestu priecinku v ktorom sa nachadzas (z ktoreho je script supsteny). 
`Permission Error` ti to hadze preto, ze si pravdepodobne niekedy otvoril subor ako administrator, alebo iba nemas pristup na citanie toho suboru.

**Comment by MagTheDev** [comment]
Neviem preco nemam pristup na tento file, a ked chcem spustut program ako admin, tak mi to nejde

**Comment by ivanhrabcak** [comment]
Fixed!
